### PR TITLE
Updates to schema

### PR DESCRIPTION
**Pull request by wtrocki**
Target for this is to update schema to be minimal and sensible to be implemented on the server. Additionally I have removed things that were hard or not possible on the server. Structure of the data is not flexible for some functionalities but we do not target here to build fully functional app. Just build an sandbox for us to test most of the graphql corner cases.

We could extend that over the time to match the requirements.
It's best to use proposal to stage that as schema on the server were out of the sync

### CODE REVIEW

**Comment by wtrocki** [comment]
Working on implementing this on the server first.

**Comment by danielpassos** [comment]
@wtrocki my only thought is if we put the like count into the Meme type when listing the memes there is no way to know if I already liked that meme.

**Comment by wtrocki** [comment]
@danielpassos yeah, but this is going to evolve over the time. 

Just want to add more stuff as:
- graph.cool is not suitable for our usage
- server side has just single object with single field implemented.

**Review by aliok — APPROVED** [review]
Looks good @wtrocki 
I like that we're doing it progressively.

**Review by darahayes — APPROVED** [review]

**Comment by danielpassos** [comment]
@wtrocki Gotcha, I'd say, let's not have like so. I think comments is enough to test the relationship scenario.

**Pull request merged**
