### PR TITLE
fix: add section that describes grafana dashboard discovery

### PR DESCRIPTION
**Pull request by darahayes**

### CODE REVIEW

**Review by david-martin — APPROVED** [review]

**Comment by david-martin** [comment]
@StevenTobin If you're happy with this, we can merge

**Review by StevenTobin — APPROVED** [review]
Yeah looks good :+1:

**Comment by david-martin** [comment]
@darahayes @StevenTobin Lets capture any jiras needed to do this in https://issues.jboss.org/browse/AEROGEAR-1814 (if we haven't already)

**Comment by darahayes** [comment]
@david-martin I think pretty much everything has been captured. Perhaps we could add a JIRA ticket to add a document to the service-docs repo to show how the dashboard discovery works + a short guide for configuring file providers.

**Comment by david-martin** [comment]
@darahayes Added a couple of docs jiras.
* 1 end user focused https://issues.jboss.org/browse/AEROGEAR-1923
* 1 development focused https://issues.jboss.org/browse/AEROGEAR-1927

**Pull request merged**
