### PR TITLE
URLs to docs from UI

### PR DESCRIPTION
**Pull request by pwright**

### CODE REVIEW

**Comment by pwright** [comment]
@jasonmadigan @laurafitzgerald  could you review please

**Review by jasonmadigan — APPROVED** [review]
This looks good to me @finp. An aside: do we capture anywhere who members of the Docs team are? Might be something to look at.

**Review by david-martin — APPROVED** [review]

**Comment by david-martin** [comment]
@laurafitzgerald since @finp tagged you for review, i'll wait for a thumbs up before merging

**Comment by pwright** [comment]
@laurafitzgerald  I think you're in the loop on this one, merging now

**Comment by laurafitzgerald** [comment]
@finp yes, sorry for the delay in getting back to you. This one makes sense.

**Pull request merged**
