### PR TITLE
Update Android SDK naming

### PR DESCRIPTION
**Pull request by aidenkeating**
@wei-lee Mind taking a look?

### CODE REVIEW

**Review by wei-lee — APPROVED** [review]
LGTM.

**Comment by wtrocki** [comment]
@aidenkeating - Added more people to PR for wider awareness

**Comment by secondsun** [comment]
So in the early days of the Aerogear project we had a lot of confusion about "Android java" and "Java SE Java".  I feel like Java on Java SE is still the default and having android instead of mobile is valuable.

At the same time mobile + Java is pretty much Android these days, and as long as the service team isn't writing Java server services in org.aerogear.mobile then I'm not going to object.

**Comment by wtrocki** [comment]
@secondsun This was updated because package names were not aligned. 
Do you think we could update package names in code and revert that at some point?
I do not know how much will be involved in terms of bom etc.

**Comment by secondsun** [comment]
@wtrocki Ahhh.  Code wins.

**Pull request merged**
