### PR TITLE
Adds refined JS SDK diagram

### PR DESCRIPTION
**Pull request by josemigallas**

### CODE REVIEW

**Review by StephenCoady — APPROVED** [review]
excellent diagram, really shows it is extensible service-wise.

**Review by paolobueno — CHANGES_REQUESTED** [review]
Awesome stuff, better way to distinguish between sdk code and existing modules.

Can you just update the html file alongside with the svg?

**Comment by josemigallas** [comment]
Done @paolobueno thanks!

**Review by paolobueno — APPROVED** [review]

**Comment by wtrocki** [comment]
Late for the party but:

**Pull request merged**
